Repository ziomciopoziomcio/autonomous-cars-env, pull requests merged in 2025-08, with the labels that each got.

#25 cleared code
  game.py
  map_generators/race_map.py
Labels: documentation, enhancement

#27 Fixing the car positioning
  game.py
Labels: fix

#28 Checkpoints counting
  game.py
Labels: enhancement

#30 Changes in collision logic and added win handling
  game.py
Labels: enhancement

#35 Screenshots customization
  .gitignore
  components/car_class.py
  game.py
Labels: enhancement

#42 Cars colour mixing error fix
  components/car_class.py
Labels: fix

#45 Screenshots switcher added with code cleaning
  components/car_class.py
  components/functions_helper.py
  game.py
  map_generators/race_map.py
Labels: documentation, enhancement

#46 Separate playercar classes
  game.py
Labels: didactics

#47 fixing the checkpoint off track problem
  map_generators/race_map.py
Labels: fix

#51 Added arrow on track generator
  game.py
Labels: enhancement
